### ISSUE TITLE
Ownership of "oy" on npm.

### ISSUE THREAD

**Issue by jamen** [revivek/oy#34]
Funny enough, I saw someone star this project on my GitHub's homepage and I also happen to own `oy` on npm.

Since I never found a use for the package, and don't think I will any time soon, I'm willing to transfer ownership to the creator(s) of this project.

Just thought I might throw that offer out there.

https://www.npmjs.com/package/oy

**Comment by jamen** [comment]
Nevermind! I own `ey`.  Well, this is embarrassing.  Haha.

**Comment by revivek** [comment]
Thanks for the offer! :)
