### ISSUE TITLE
Language information and text direction

### ISSUE THREAD

**Issue by dleshem** [revivek/oy#36]
We use Oy for sending internationalized emails, including in RTL languages like Hebrew and Arabic.

For best results, we need to control the generated HTML's "lang" and "dir" attributes ([see this](https://www.w3.org/TR/html4/struct/dirlang.html)). 

Seems like the natural way would be to pass "lang" and "dir" as arguments to HTML4.generateDefaultTemplate, and (if given) add them as &lt;html&gt; tag attributes in that function.

I can submit a pull request if you want. Should be a pretty straightforward change though :)

**Comment by revivek** [comment]
Sounds like an important feature, and I think adding it as an option in `generateDefaultTemplate` makes sense. I'll

**Comment by dleshem** [comment]
Awesome, your commit is exactly what we need.

Consider escaping the user-controlled `dir` and `lang` values when adding them as raw HTML. This will protect careless users who pass unsanitized values, which unfortunately is a common scenario.

Any chance you can release this feature to npm? We'd love to start using it :)

**Comment by revivek** [comment]
Great, I'll merge it in then. With regards to escaping the `dir` and `lang`, doing so would be safer though I think this opens up a larger question of what else should be escaped (i.e. `title`, `headCSS`, `previewText`, and I see an issue in `bodyContent` as well). Would you mind opening a separate issue on this conversation?

Sure thing, you should expect a 0.5.0 version released in the next day or two.

**Comment by revivek** [comment]
Released

**Comment by dleshem** [comment]
Thanks Vivek, much appreciated!
