### ISSUE TITLE
Css-modules styles -> would this work ?

### ISSUE THREAD

**Issue by andreimc** [revivek/oy#46]
Hey Vivek,

I have a react project and I would like to use this with css-modules styles.

Have you used it with that in the past ?

Regards,
Andrei

**Comment by revivek** [comment]
Hi Andrei, are you referring to [this project called "react-css-modules"](https://github.com/gajus/react-css-modules)? I know that setting the `styles` prop for elements with webpack's `css-loader` should work as expected. I would expect the CSSModules wrapper component to work fine with the current Oy versions, though I have suspicions about how the wrapper component will interact with the upcoming Oy `1.0.0-rc1` release, stemming from the fact that both libs do some pre-rendering to manipulate the rendered elements. If you're interested in investigating compatibility more, I'd suggest checking out the [`next` branch](https://github.com/revivek/oy/tree/next) and creating a simple setup. Hope this helps!
