### ISSUE TITLE
Other background color then white

### ISSUE THREAD

**Issue by mikegazdag** [revivek/oy#50]
I'm curious as to why this module forces the `body`  background to be white? And also being an inline styles, this takes precedence over any `headCSS` passed in. I have an email that has a full page blue  background, and I'm unable to edit this without editing the `node_module`.

**Comment by mikegazdag** [comment]
Secondly, further investigation, shows that using the `headCSS` to overwrite the inline styles on these lines (see below), is fruitless, as gmail will just strip out the entire `<style>` block. 

```html
 <body bgcolor="#FFFFFF" width="100%" style="-webkit-font-smoothing: antialiased; width:100% !important; background:#FFFFFF;-webkit-text-size-adjust:none; margin:0; padding:0; min-width:100%">
          <table bgcolor="#FFFFFF" id="__bodyTable__" width="100%" style="-webkit-font-smoothing: antialiased; width:100% !important; background:#FFFFFF;-webkit-text-size-adjust:none; margin:0; padding:0; min-width:100%">
```

**Comment by mikegazdag** [comment]
Just discovered the `generateCustomTemplate` function, my issues are resolved.

**Comment by revivek** [comment]
Glad you found a way for this to work! I realize the custom template function isn't documented anywhere, which should change. Created #51
