### ISSUE TITLE
RTL not working in gmail

### ISSUE THREAD

**Issue by malsomnus** [revivek/oy#53]
(This issue might also exist in services other than gmail)

When rendering an email with dir: 'rtl', the email is not displayed correct in gmail.
I solved this by adding "direction: ${dir}" to the <body> tag's style.

**Comment by revivek** [comment]
Thanks for the report. What tag are you referring to?

**Comment by malsomnus** [comment]
Sorry, I was referring to the <body> tag.

**Comment by revivek** [comment]
Just tested on gmail, and it seems like that's indeed the case. Will submit a fix for this soon.
