### ISSUE TITLE
Upgrade to React 15.3.0

### ISSUE THREAD

**Issue by revivek** [revivek/oy#56]
See #55.

**Comment by rkoberg** [comment]
I am using react 15.3 and getting lots of warnings like:
```
Warning: You are manually calling a React.PropTypes validation function for the `color` prop on `Footer`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```
Does the next branch handle these warnings? (Not really seeing fixes for these types of warnings in that branch from a quick look.)

**Comment by revivek** [comment]
Not yet, sorry. The warnings aren't resolved in `master` or `next`. If you'd like to avoid them, you'll have to use 15.1.0 for now.

**Comment by revivek** [comment]
Fixed on master.
