### ISSUE TITLE
headCSS gets stripped of when the email is sent 

### ISSUE THREAD

**Issue by ravic1995** [revivek/oy#60]
I am using sendgrid to send emails 
When I pass in the string of HTML generated by the renderTemplate function the HEAD css gets stripped out.

**Comment by revivek** [comment]
Are you seeing that in your email client? Some email clients strip the CSS in <head> due to security reasons, so you can't count on that always existing.

**Comment by ravic1995** [comment]
Yes I am seeing that happen in the email clients. 
Is there a way to reuse the components on my react website in the email.
The react components on the website are written using containers and not table tags.

**Comment by revivek** [comment]
Got it, yeah, email clients like Gmail strips out the head tag entirely, so you can't rely on CSS in the head. Using inline styles is the best way to ensure cross-client compatibility.

Unfortunately no, components need to be built with table elements. The nice thing about React is that you should only have to do this once per component, after which these components can be reused.
