### ISSUE TITLE
Update PropTypes to prevent false positive warning about manually calling PropTypes

### ISSUE THREAD

**Issue by STEVEOO6** [revivek/oy#61]
After adding standard propTypes definition on a component, I receive multiple warnings during render. For example:

"Warning: You are manually calling a React.PropTypes validation function for the `heading` prop on `ReportHeader`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details."

**Comment by revivek** [comment]
What version of Oy are you using? On the most recent 0.7.0, I added a propTypes definition to the EmptySpace element in the Hello World example, and unfortunately wasn't able to reproduce your message.

**Comment by samybob1** [comment]
I have the same warnings using `oy-vey` 0.7.0, here is the component I use:

```jsx
import React from 'react';

import EmailLayoutComponent from '/imports/ui/components/layouts/EmailLayoutComponent';
import EmailHeaderComponent from '/imports/ui/components/parts/emails/EmailHeaderComponent';
import EmailBodyComponent from '/imports/ui/components/parts/emails/EmailBodyComponent';
import EmailFooterComponent from '/imports/ui/components/parts/emails/EmailFooterComponent';

class BuyEmailComponent extends React.PureComponent {
  static propTypes = {
    customer: React.PropTypes.object.isRequired,
    tickets: React.PropTypes.number.isRequired,
  };

  render() {
    return (
      <EmailLayoutComponent>
        <EmailHeaderComponent/>
        <EmailBodyComponent>
          Le client {this.props.customer.username} souhaite acheter {this.props.tickets} tickets.
        </EmailBodyComponent>
        <EmailFooterComponent/>
      </EmailLayoutComponent>
    );
  }
}

export default BuyEmailComponent;
```

And the warnings I get:

>Warning: You are manually calling a React.PropTypes validation function for the `customer` prop on `BuyEmailComponent`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
>Warning: You are manually calling a React.PropTypes validation function for the `tickets` prop on `BuyEmailComponent`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by icd2k3** [comment]
Seeing this same issue

**Comment by Rendez** [comment]
Hi @icd2k3, @STEVEOO6, @samybob1, just made this PR (https://github.com/revivek/oy/pull/65). Could you test that it also eliminates the warnings in your case(s)?

**Comment by revivek** [comment]
I've published 0.8.0, which includes the PR that @Rendez mentions. Can you verify that the new version fixes your issues?

**Comment by icd2k3** [comment]
Works for me - thanks @revivek!

**Comment by Rendez** [comment]
@revivek seems like npm caught the 0.8.0 update, but you didn't create a tag and push it to remote. I guess they look at the package.json only.

**Comment by revivek** [comment]
Thanks, done.
