### ISSUE TITLE
CleanCSS Shorthand Compacting adjusting hex color codes to incompatible form

### ISSUE THREAD

**Issue by STEVEOO6** [revivek/oy#62]
3 digit hex color codes are not uniformly supported across some legacy email clients.

Currently this library is using CleanCSS to minify provided CSS, which uses 'shorthand compacting' to convert 6 digit hex color codes to 3 digit hex color codes where appropriate.

Given that this library is focused on email rendering, it may make sense to set the CleanCSS' shorthandCompacting option to false by default. Alternatively allowing the user to configure which options a provided to the CleanCSS constructor may be useful and provide the desired functionality where required.

**Comment by revivek** [comment]
Thanks for catching this. That compacting shouldn't be happening.
