### ISSUE TITLE
why is `previewText` required?

### ISSUE THREAD

**Issue by jampy** [revivek/oy#67]
`previewText` is an required option, but as far as I can tell it's just added to an invisible `<span>`. It's not clear to me why it's necessary or what's it's use really.

Whats the problem with omitting that invisible element? Which clients benefit from it and what is a good/correct `previewText`? 

Can you clarify, please?

**Comment by Rendez** [comment]
@jampy I would start by reading this article on the preview text benefits https://litmus.com/blog/the-ultimate-guide-to-preview-text-support

We could perhaps make it optional, but on the same note you could also use your own custom template then.

Let me know if that clarified things a little bit more.

**Comment by jampy** [comment]
Thanks for the link - very interesting article.

Yeah, I think that `previewText` should be optional without needing to create a custom template just for that.
