### ISSUE TITLE
Issue with import react components on server

### ISSUE THREAD

**Issue by yashwanthm** [revivek/oy#80]
Great idea! This would save a lot of time for my team. 
I'm facing an issue while using the imported react component. What is going wrong here? 
Is this related to how the component needed to be done?
```
var React = require('react');
var Oy = require('oy-vey')
const {Table, TBody, TR, TD} = Oy;
var tempalte = require('../views/emails/react/template.jsx');

```
```
 const html = Oy.renderTemplate(<Template  />, {,^, SyntaxError: Unexpected token <,     at Object.exports.runInThisContext (vm.js:73:16),     at Module._compile (module.js:543:28),     at Object.Module._extensions..js (module.js:580:10),     at Module.load (module.js:488:32),     at tryModuleLoad (module.js:447:12),     at Function.Module._load (module.js:439:3),     at Module.require (module.js:498:17)

```

Component - template.jsx
```
//switched to require instead of import.
var React = require('react');
var { Grid, Row, Col } = require('react-flexbox-grid');
const {Table, TBody, TR, TD} = Oy;
export default (props) => {
//a lot of lines that return react code
}
```

I have also noticed Illegal export declaration error.

**Comment by Rendez** [comment]
I'm going to guess here you're not running your node server with node-babel. Without babel you don't have support for JSX and any other ES6 lang. features you might be using, such as export.

**Comment by yashwanthm** [comment]
@Rendez You're right. It took me a while to realise. The backend server is largely node only and I do not have react or babel setup and thats how most non full-stack apps would be I think. Can we look into a way to still get this working ? I've tried using http://infoheap.com/online-react-jsx-to-javascript/ to transform JSX to JS and trying to figure out ways.

**Comment by Rendez** [comment]
The best way IMO would be to run your node process using `babel-node` for development, and use `babel-cli` to compile your ES6+JSX code into node 6-8 compatible ES2015 code for production, since babel-node isn't fast enough for a live environment.

- Running node process using babel-node: https://babeljs.io/docs/usage/cli/#babel-node-usage
- Compiling files into ES2015: https://babeljs.io/docs/usage/cli/#babel-compile-files

**Comment by revivek** [comment]
Closing this issue because it's out of the scope of this particular library. Thanks for helping, @Rendez! @yashwanthm I share Luis' recommendations. `babel-node` works great for development. It may even work fine for other "offline" cases where fast server response times aren't critical.
